select  * from (

select 
--A1_NOME,US_NOME,
case WHEN UA_PROSPEC='F' THEN 'CLIENTE' ELSE 'PROSPECT' END TIPO,
case WHEN UA_PROSPEC='F' THEN A1_NOME ELSE US_NOME END NOME,
case WHEN UA_PROSPEC='F' THEN A1_CGC ELSE US_CGC END CNPJ,
UA_FILIAL
--,* 
from SUA010 SUA (NOLOCK)
LEFT JOIN SA1010 SA1 (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= A1_FILIAL AND UA_CLIENTE=A1_COD AND UA_LOJA= A1_LOJA AND UA_PROSPEC='F' AND SA1.D_E_L_E_T_=''
LEFT JOIN SUS010 SUS (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= US_FILIAL AND UA_CLIENTE=US_COD AND UA_LOJA= US_LOJA AND UA_PROSPEC='T' AND SUS.D_E_L_E_T_=''

) aa
GROUP BY TIPO,	NOME,	CNPJ,	UA_FILIAL
--UA_CLIENTE	UA_LOJA
--930672	0001
--UA_PROSPEC
--F
--WHERE UA_NUM IN ('062487','062486')
--AND A1_NOME IS NOT NULL

--SELECT * FROM SUS010

