SELECT E1_FILIAL,A1_COD, E1_CLIENTE CLIENTE, E1_LOJA LOJA, E1_NOMCLI NOME, A1_EST ESTADO, E1_NUM TITULO,	E1_TIPO, E1_EMISSAO EMISSAO, E1_VENCTO VENCIMENTO,
E1_VALOR VALOR, E1_DESCONT DESCONTO, E1_JUROS JUROS, E1_VALJUR TAXA_PERMAN, E1_PORCJUR PERC_JUROS_DIARIO, 
E1_VLCRUZ VLR_MOEDA_NAC, E1_VALLIQ VLR_LIQ_BAIXA,
E1_BAIXA DT_BAIXA, E1_STATUS STATUS_TIT FROM SE1010 SE1
INNER JOIN SA1010 SA1 (NOLOCK) ON (SUBSTRING(SE1.E1_FILIAL,1,4)= SA1.A1_FILIAL AND SE1.E1_CLIENTE = SA1.A1_COD AND SA1.D_E_L_E_T_ = ' ' )
WHERE 1=1
--AND E1_FILIAL = '010101'
AND SE1.D_E_L_E_T_ <> '*'
AND A1_EST = 'EX'
AND E1_STATUS = 'B'
AND E1_BAIXA <= '20201231'

ORDER BY E1_BAIXA