select 
M_NAME,M_MODULE,M_ARQMENU,
N3.N_DESC DESC3,N2.N_DESC DESC2, N1.N_DESC DESC1,F_FUNCTION
--, M3.I_ORDER,M2.I_ORDER,M1.I_ORDER
--,* 
from MPMENU_ITEM M1
LEFT JOIN MPMENU_ITEM M2 ON M1.I_FATHER=M2.I_ID
JOIN MPMENU_ITEM M3 ON M2.I_FATHER=M3.I_ID
LEFT join MPMENU_I18N N1 on M1.I_ID=N1.N_PAREN_ID
LEFT join MPMENU_I18N N2 on M2.I_ID=N2.N_PAREN_ID
LEFT join MPMENU_I18N N3 on M3.I_ID=N3.N_PAREN_ID
JOIN MPMENU_MENU MN ON M3.I_ID_MENU = MN.M_ID
left JOIN MPMENU_FUNCTION MF ON M1.I_ID_FUNC = MF.F_ID
WHERE 1=1
and F_FUNCTION='CRMA980'
--and M_NAME in('SIGAPON','SIGACON')
--and M_NAME like'%SIGATMK%'                                     
--and M_NAME='SUPERVISOR TQ'                                     
--and M1.I_ID_MENU ='A740BFC0081040009104126662A477E6'
AND (N1.N_LANG='1' OR N1.N_LANG IS NULL)
AND (N2.N_LANG='1' OR N2.N_LANG IS NULL)
AND (N3.N_LANG='1' OR N3.N_LANG IS NULL)
--AND N2.N_DESC='Específicos'
--AND N1.N_DESC LIKE '%Manual %'
--AND M_ARQMENU='#BKP_SIGATMK#20211126T1451'
order by M_NAME, M_MODULE,M3.I_ORDER,M2.I_ORDER,M1.I_ORDER


--SELECT * FROM MPMENU_MENU
--WHERE 1=1
--AND M_NAME like'%SIGATMK%' 
--ORDER BY M_NAME





