DECLARE @PRODUTO CHAR(20) = '009996'
DECLARE @CODCLI CHAR(6) = '044040'
DECLARE @LOJACLI CHAR(4) = '0001'



--Encontra o cliente
--SELECT A1_COD, A1_LOJA, A1_NOME, A1_NREDUZ, A1_TIPO, A1_PESSOA FROM SA1010 WHERE A1_NOME LIKE '%MOKVA%' AND D_E_L_E_T_ = ''

SELECT B1_GRTRIB, B1_GRPTI, B1_ORIGEM FROM SB1010 WHERE B1_COD = @PRODUTO AND D_E_L_E_T_ = ''
--SELECT A1_GRPTRIB, A1_TIPO, A1_PESSOA, A1_CONTRIB, A1_SIMPLES FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = ''
SELECT US_GRPTRIB,US_PESSOA,US_TIPO,* FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = ''
--SELECT A1_EST FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = ''
SELECT US_EST FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = ''
--SELECT * FROM SX5010 WHERE X5_TABELA = '21'

DECLARE @GRUPO_PRODUTO CHAR(3) = (SELECT B1_GRTRIB FROM SB1010 WHERE B1_COD = @PRODUTO AND D_E_L_E_T_ = '')
--DECLARE @GRUPO_CLIENTE CHAR(3) = (SELECT A1_GRPTRIB FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = '')
DECLARE @GRUPO_CLIENTE CHAR(3) = (SELECT US_GRPTRIB FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = '')
--DECLARE @ESTADO_CLIENTE CHAR(2) = (SELECT A1_EST FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = '')
DECLARE @ESTADO_CLIENTE CHAR(2) = (SELECT US_EST FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = '')
DECLARE @OPERACAO CHAR(2) = '01'
DECLARE @FILIAL CHAR(2) = ''
DECLARE @GRPTI CHAR(4) = ''

--SELECT B1_CLASFIS,* FROM SB1010 WHEB1_CLASFISRE B1_COD='009996'

--SELECT *
--FROM SF7010
--WHERE 1=1
--AND D_E_L_E_T_ = ''
--AND F7_GRTRIB = '006'
--AND F7_EST = 'AM'
--AND F7_GRPCLI = '001'

--SELECT *
--FROM SFM010
--WHERE FM_FILIAL = '03'
--AND D_E_L_E_T_ = ''
--AND FM_TIPO = '03'
--AND FM_GRPROD = '013'
--AND FM_GRTRIB = '006'
--AND FM_GRPTI = ''

--OPERAÇÕES
--01: VENDA
--03: VENDA CONSUMIDOR FINAL

--SELECT * FROM SB2010 WHERE B2_COD = 'HLX1502V' AND B2_FILIAL = '04'

SELECT
	'REGRA 01' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = @PRODUTO
	AND FM_GRTRIB = @GRUPO_CLIENTE
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	--AND FM_GRPTI = @GRPTI
	AND D_E_L_E_T_ = ''
UNION ALL 
SELECT
	'REGRA 02' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = @PRODUTO
	AND FM_GRTRIB = ''
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
	UNION ALL 

SELECT
	'REGRA 03' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = @GRUPO_CLIENTE
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
UNION ALL 


SELECT
	'REGRA 04' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = @PRODUTO
	AND FM_GRTRIB = ''
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = ''
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
UNION ALL

SELECT
	'REGRA 05' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = @GRUPO_CLIENTE
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = ''
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
	
UNION ALL 

SELECT
	'REGRA 06' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = ''
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST =  @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
UNION ALL

SELECT
	'REGRA 07' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = @GRUPO_CLIENTE
	AND FM_GRPROD = ''
	AND FM_EST = @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
UNION ALL


SELECT
	'REGRA 08' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = ''
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = ''
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
UNION ALL
SELECT
	'REGRA 09' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = @GRUPO_CLIENTE
	AND FM_GRPROD = ''
	AND FM_EST = ''
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI
UNION ALL

SELECT
	'REGRA 10' REGRA,
	*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = @FILIAL
	AND FM_PRODUTO = ''
	AND FM_GRTRIB = ''
	AND FM_GRPROD = ''
	AND FM_EST = @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	AND D_E_L_E_T_ = ''
	--AND FM_GRPTI = @GRPTI;
