
	select * from SC2010 where C2_FILIAL = '010102'

	select * from SHF010 where HF_FILIAL = '010102'

	select * from SHC010 where HC_FILIAL = '010102'
	
	select * from SH6010 where  1=1	AND H6_FILIAL = '010102' AND H6_DTPROD >= '20240101' AND H6_DTPROD <= '20240701'


			SELECT DISTINCT
					H6_RECURSO AS MAQUINA,
					H6_PRODUTO AS PRODUTO,
					H6_OP AS ORDEM_PRODUÇÃO,
					CAST(H6_DTPROD AS DATE) AS DATA_PRODUÇÃO,
					H6_HORAINI AS HORA_INICIO,
					H6_HORAFIN AS HORA_FIM,
					DATEDIFF(MINUTE, CAST(CONCAT(H6_DATAINI, ' ', H6_HORAINI) AS DATETIME), CAST(CONCAT(H6_DATAFIN, ' ',H6_HORAFIN) AS DATETIME)) as TMP_DECORRIDO,
					CAST(CONCAT(H6_DATAINI, ' ', H6_HORAINI) AS DATE) AS DATAINI,
					CAST(CONCAT(H6_DATAFIN, ' ', H6_HORAFIN) AS DATE) AS DATAFIM,
					SUM(H6_QTDPROD) AS QUANTI_PRODUZIDA,
					H6_QTDPERD AS RESÍDUO,
					ROUND(CASE 
						WHEN (SUM(H6_QTDPROD)/50) <= 0 OR 
							 (DATEDIFF(MINUTE, CAST(CONCAT(H6_DATAINI, ' ', H6_HORAINI) AS DATETIME), 
							 CAST(CONCAT(H6_DATAFIN, ' ', H6_HORAFIN) AS DATETIME)) / 60) <= 0 THEN 99999999999.99
						ELSE (SUM(H6_QTDPROD)/50) / 
							 (DATEDIFF(MINUTE, CAST(CONCAT(H6_DATAINI, ' ', H6_HORAINI) AS DATETIME), 
							 CAST(CONCAT(H6_DATAFIN, ' ', H6_HORAFIN) AS DATETIME)) / 60)
					END, 2) AS ROLO_P_HORA,
					H6_XPRDIDE as PRUDUCAO_IDEAL
				FROM SH6010 
				WHERE 1=1
			AND H6_FILIAL = '010102'
			AND H6_DTPROD >= '20240308'
			AND H6_DTPROD <= '20240308'
			GROUP BY H6_OP,H6_PRODUTO,H6_DTPROD,H6_HORAINI,H6_HORAFIN,H6_DATAINI,H6_DATAFIN,H6_QTDPERD,H6_QTDPROD,H6_FILIAL,H6_RECURSO,H6_XPRDIDE


			SELECT USR_DEPTO 
				FROM SYS_USR 
					WHERE 1=1
						AND USR_CODIGO = 'RODRIGOS-TG'

			SELECT U7_CODVEN 
				FROM SU7010 
					WHERE 1=1
						AND U7_NREDUZ = 'RODRIGOS-TG'
						AND D_E_L_E_T_ = ''
						AND U7_FILIAL = '020101'

				SELECT	UA_NUM,
						UA_VEND
					FROM SUA010 
						WHERE UA_NUM = ''




select * from SC7010 where C7_PRODUTO = '036018'