SELECT TEMP.*
 ,D2_DOC,D2_ITEM, D2_PEDIDO,--D2_DESC,
 C6_DESCRI, D2_QUANT, D2_PRCVEN, D2_VALBRUT, D2_TOTAL
,V.* 
FROM (
SELECT F2_FILIAL, F2_CLIENTE, F2_LOJA, MAX(F2_EMISSAO)ULT_EMISS, MAX(F2_DOC) ULT_DOC ,
A1_COD, A1_LOJA, A1_NOME, A1_CGC, A1_EST, A1_MUN, A1_DDD, A1_TEL, A1_ULTCOM, A1_CODSEG, AOV_DESSEG 
FROM SF2010 SF2 (NOLOCK)
LEFT JOIN SA1010 SA1 (NOLOCK) ON (A1_FILIAL=SUBSTRING(F2_FILIAL,1,4) AND A1_COD=F2_CLIENTE AND A1_LOJA=F2_LOJA AND SA1.D_E_L_E_T_='')
LEFT JOIN AOV010 AOV (NOLOCK) ON (AOV_FILIAL = SA1.A1_FILIAL AND AOV.AOV_CODSEG = SA1.A1_CODSEG  AND AOV.D_E_L_E_T_ = ' '  ) 
WHERE 1=1
AND F2_FILIAL='010101'
AND F2_CLIENTE='027915'
AND F2_TIPO='N'
AND SF2.D_E_L_E_T_=''
GROUP BY F2_FILIAL,F2_CLIENTE,F2_LOJA,
A1_COD, A1_LOJA, A1_NOME, A1_CGC, A1_EST, A1_MUN, A1_DDD, A1_TEL,  A1_ULTCOM, A1_CODSEG, AOV_DESSEG 
)TEMP
JOIN SD2010 SD2 (NOLOCK) ON (D2_FILIAL=F2_FILIAL AND D2_DOC=ULT_DOC AND SD2.D_E_L_E_T_='')
JOIN SC6010 SC6 (NOLOCK) ON (D2_FILIAL=C6_FILIAL AND D2_PEDIDO=C6_NUM AND D2_ITEM= C6_ITEM AND SC6.D_E_L_E_T_='')
LEFT JOIN (select * from V_CLIENTE_ATEND)V ON FILIAL=SUBSTRING(F2_FILIAL,1,4) AND TIPO='CLIENTE' AND CLIENTE=F2_CLIENTE AND LOJA=F2_LOJA



