
-- PROBLEMA: AO EXCLUIR UMA OP OS CAMPOS C6_OP, C6_NUMOP E C6_ITEMOP ESTÃO PREENCHIDOS DE FORMA INCORRETA

--LIMPA OS CAMPOS C6_NUMOP E C6_ITEMOP E ATRIBUI O STATUS 07 NO CAMPO C6_OP


DECLARE @C6 AS VARCHAR(6)  --DEFINE VARIVEL @@C6 QUE RECEBRA O NUMERO DO PEDIDO A SER UTILIZADO 
DECLARE @FILIAL AS VARCHAR(6) -- DEFINE VARIAVEL @FILIAL QUE RECEBE A FILIAL A SER UTILIZADA


SET @FILIAL  = '020101' --ATRIBUI O VALOR A VARIVEL @FILIAL  
SET @C6 = '041739' -- ATRIBUI O VALOR A VARIVAL @C6


SELECT C6_NUM, C6_OP,C6_NUMOP, C6_ITEMOP FROM SC6010 WHERE C6_NUM = @C6 AND C6_FILIAL = @FILIAL	  

BEGIN TRANSACTION

UPDATE SC6010 SET C6_OP = '07', C6_NUMOP = '', C6_ITEMOP = ''
WHERE C6_FILIAL = @FILIAL
AND C6_NUM = @C6


SELECT C6_NUM, C6_OP,C6_NUMOP, C6_ITEMOP FROM SC6010 WHERE C6_NUM = @C6 AND C6_FILIAL = @FILIAL	


--COMMIT

--ROLLBACK