ALTER FUNCTION dbo.BUSCADESC (@CHAVE VARCHAR(8)) 
 RETURNS VARCHAR(MAX)
 BEGIN

 DECLARE @DESC AS VARCHAR(MAX)

 SELECT @DESC = (COALESCE(
        (SELECT CAST(LTRIM(RTRIM(YP_TEXTO))+' ' AS VARCHAR(48)) AS [text()]
         FROM SYP010 AS O (NOLOCK)
         WHERE O.YP_CHAVE = C.YP_CHAVE
         ORDER BY YP_SEQ
         FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '')
		 )

FROM SYP010 AS C (NOLOCK)
WHERE YP_CHAVE = @CHAVE
GROUP BY YP_CHAVE
RETURN @DESC
END
GO

SELECT dbo.BUSCADESC('245447')