
SELECT *
	/*B8_LOTECTL, B8_FABRICA, B1_COD, B1_CODBAR, B1_TIPO,
	BM_GRUPO, BM_DESC, B1_DESC, B8_MALHA, 
	CASE WHEN BF_LOCALIZ IS NULL THEN '-' else BF_LOCALIZ END AS BF_LOCALIZ,
	B8_DOC, B1_GRUPO, B8_LOTEFOR, B8_COR, B8_DATA,
	B8_TRATAME, B8_TESSITU, B8_SALDO, B8_DEFEITO,
	B8_PEDACOS,	B8_LARGURA, B1_LARGURA, B8_ORIGEM,
	B8_NROFIOS, B8_DEVNF, B8_DFABRIC, B8_ORIGLAN,
	B8_CLIFOR, B8_LOJA, B8_ACABAME, B8_DESENHO,
	B8_ESPESSU, B8_AISI, B8_MICRAGE, B8_GRAMATU,
	B8_COMPRIM, B8_INVOICE, B8_FUROS, B8_QUALIDA,
	B8_TURNO, B8_DIAMETR, B8_OBS, B8_ROLO, B8_PESO, B8_UV*/
	FROM SB8010 SB8
	FULL JOIN SBF010 SBF ON 1=1
	 AND B8_PRODUTO = BF_PRODUTO
	 AND B8_LOTECTL = BF_LOTECTL
	 AND B8_FILIAL = BF_FILIAL
	 AND BF_QUANT > 0
	 INNER JOIN	SB1010 SB1 ON 1=1
	 AND B8_PRODUTO = B1_COD
	 AND B1_FILIAL = B8_FILIAL
	INNER JOIN SBM010 SBM ON 1=1
	 AND B1_GRUPO = BM_GRUPO
	 AND B1_FILIAL = BM_FILIAL
	 WHERE B8_FILIAL= '010102'
	AND SB1.D_E_L_E_T_='' AND SB8.D_E_L_E_T_='' AND SBM.D_E_L_E_T_=''
	 AND B8_SALDO>0  
	 AND B8_DOC between 	'' AND 'ZZZZZZZZZ' 
	AND B1_COD between 	'' AND 'ZZZZZZ'    
	 AND B1_GRUPO between 	'' AND 'ZZZZ'  
	AND B1_TIPO between 	'' AND 'ZZ'    
	 AND B8_LOCAL between 	'' AND 'ZZ'    
	 AND B8_LOTECTL between '0000204845 ' AND '0000204845'   
	 