--BEGIN TRANSACTION INSERT INTO CTD010 (CTD_FILIAL,	CTD_ITEM,	CTD_CLASSE,	CTD_NORMAL,	CTD_DESC01,CTD_ITLP,	CTD_BLOQ,CTD_CLOBRG,CTD_ACCLVL,	CTD_DTEXIS,	CTD010.R_E_C_N_O_)

select 
A2_FILIAL CTD_FILIAL,
'F'+A2_COD+A2_LOJA CTD_ITEM,
'2'CTD_CLASSE,
''CTD_NORMAL,
SUBSTRING(A2_NOME,1,40) CTD_DESC01,
'F'+A2_COD+A2_LOJA CTD_ITLP,
'2'CTD_BLOQ,
'2'CTD_CLOBRG,
'1'CTD_ACCLVL,
'19800101'CTD_DTEXIS,
(SELECT ISNULL(MAX(R_E_C_N_O_),0) FROM CTD010)+ rank() OVER (ORDER BY A2_FILIAL, A2_COD , A2_LOJA	) R_E_C_N_O_
from(
	select CTD_ITEM,SA2.* from SA2010 SA2
	LEFT JOIN CTD010 ON CTD_FILIAL= A2_FILIAL AND CTD_ITEM= 'F'+A2_COD+A2_LOJA
	where 1=1
	--AND A2_FILIAL= '0101'
	AND CTD_ITEM IS NULL
	--AND A2_DTCAD >='20200601'
	AND SA2.D_E_L_E_T_=''
	AND A2_COD NOT IN ('ESTADO','000002')
)AAA
--commit
--ROLLBACK
--select * from CTD010
