--ORÇAMENTO ->


SELECT 
UA_FILIAL,	UA_NUM,	UA_NUMSC5,	UA_DOC,	
CASE WHEN C5_DEL ='*' THEN 'PEDIDO EXCLUIDO' ELSE UA_STATUS END UA_STATUS,
UA_EMISSAO,	UA_CLIENTE,	UA_LOJA,	NOMECLI,
TIPOCLI,	UA_VALMERC,	UA_VLRLIQ,	UA_VEND,	A3_NOME,	UA_OPERADO,UA_CODCANC,	U7_NOME FROM (
select UA_FILIAL, UA_NUM ,UA_NUMSC5 , UA_DOC , UA_STATUS, UA_EMISSAO, UA_CLIENTE, UA_LOJA, 

(SELECT SC5.D_E_L_E_T_ FROM SC5010 SC5 (NOLOCK) WHERE C5_FILIAL=UA_FILIAL AND C5_NUM=UA_NUMSC5 )C5_DEL,

CASE WHEN UA_PROSPEC='F' THEN A1_NOME  ELSE US_NOME END NOMECLI,
CASE WHEN UA_PROSPEC='F' THEN 'CLIENTE'  ELSE 'PROSPECT' END TIPOCLI,
UA_VALMERC,	UA_VLRLIQ,
UA_VEND,A3_NOME , 
UA_OPERADO,UA_CODCANC,U7_NOME 
from SUA010 SUA (NOLOCK)
LEFT JOIN SA1010 SA1 (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= A1_FILIAL AND UA_CLIENTE=A1_COD AND UA_LOJA= A1_LOJA AND UA_PROSPEC='F' AND SA1.D_E_L_E_T_=''
LEFT JOIN SUS010 SUS (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= US_FILIAL AND UA_CLIENTE=US_COD AND UA_LOJA= US_LOJA AND UA_PROSPEC='T' AND SUS.D_E_L_E_T_=''
INNER JOIN SA3010 SA3 (NOLOCK)ON SUBSTRING(UA_FILIAL,1,4)= A3_FILIAL AND A3_COD =UA_VEND AND SA3.D_E_L_E_T_=''												 
INNER JOIN SU7010 SU7 (NOLOCK)ON UA_FILIAL= U7_FILIAL AND U7_COD =UA_OPERADO AND SU7.D_E_L_E_T_=''												 
WHERE UA_OPER IN ('1','2')
AND UA_VEND='000014'
AND UA_EMISSAO BETWEEN'20200101' AND '20210709'
AND UA_NUMSC5<>''
)TEMP
WHERE 1=1
AND UA_STATUS='CAN'
--AND C5_DEL='*'
ORDER BY UA_NUM




--ATENDIMENTO ->
SELECT UA_FILIAL, UA_NUM, UA_EMISSAO, UA_CLIENTE, UA_LOJA, 
CASE WHEN UA_PROSPEC='F' THEN A1_NOME  ELSE US_NOME END NOMECLI,
CASE WHEN UA_PROSPEC='F' THEN 'CLIENTE'  ELSE 'PROSPECT' END TIPOCLI,
UA_VEND,A3_NOME, 
UA_OPERADO,U7_NOME,
CONVERT(varchar(MAX),CONVERT(VARBINARY(MAX), UA_XOBS)) UA_XOBS2
from SUA010 SUA (NOLOCK)
LEFT JOIN SA1010 SA1 (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= A1_FILIAL AND UA_CLIENTE=A1_COD AND UA_LOJA= A1_LOJA AND UA_PROSPEC='F' AND SA1.D_E_L_E_T_=''
LEFT JOIN SUS010 SUS (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= US_FILIAL AND UA_CLIENTE=US_COD AND UA_LOJA= US_LOJA AND UA_PROSPEC='T' AND SUS.D_E_L_E_T_=''
INNER JOIN SA3010 SA3 (NOLOCK)ON SUBSTRING(UA_FILIAL,1,4)= A3_FILIAL AND A3_COD =UA_VEND AND SA3.D_E_L_E_T_=''												 
INNER JOIN SU7010 SU7 (NOLOCK)ON UA_FILIAL= U7_FILIAL AND U7_COD =UA_OPERADO AND SU7.D_E_L_E_T_=''												 
WHERE UA_OPER ='3'
AND UA_VEND='000014'
AND UA_EMISSAO BETWEEN'20200101' AND '20210709'
ORDER BY UA_NUM
