SELECT 
* 
--begin TRANSACTION UPDATE CTG SET CTG_STATUS='1'
FROM CTG010 CTG

SELECT * 
--BEGIN TRANSACTION UPDATE CQD SET CQD_STATUS='1'
FROM CQD010 CQD
WHERE 1=1
--AND CQD_DESC IN('Financeiro – Contas a Pagar','Financeiro – Contas a Receber')
AND CQD_FILIAL='010101'
AND CQD_EXERC='2021'
AND CQD_PERIOD='12'

--COMMIT