--relatorio atendimentos marketing
select 
UA_FILIAL
,UA_NUM
,UA_CLIENTE
--,UA_LOJA
,case WHEN UA_PROSPEC='F' THEN 'CLIENTE' ELSE 'PROSPECT' END TIPO
,case WHEN UA_PROSPEC='F' THEN A1_NOME ELSE US_NOME END NOME
,case WHEN UA_PROSPEC='F' THEN A1_CGC ELSE US_CGC END CNPJ
,case WHEN UA_PROSPEC='F' THEN A1_EMAIL else US_EMAIL END EMAIL
,U5_CONTAT
--,U5_CELULAR
--,U5_FCOM1
--,U5_EMAIL
--,U5_FONE
--,UA_MIDIA
,UH_DESC MIDIA
,UA_VEND
,A3_NOME
--,UA_TMK
--,UA_OPER--1=Faturamento;2=Orcamento;3=Atendimento  
,CASE WHEN UA_OPER ='1' THEN 'FATURAMENTO'
	  WHEN UA_OPER ='2' THEN 'ORÇAMENTO'
	  ELSE 'ATENDIMENTO'
END OPERACAO
,UA_EMISSAO
,UA_INICIO
,UA_XMOBS
--,UA_XOBS
,CONVERT(varchar(MAX),CONVERT(VARBINARY(MAX), UA_XOBS)) as XOBS
,CONVERT(varchar(MAX),CONVERT(VARBINARY(MAX), UA_XOBSMKT)) as XOBSMKT
--,UA_XOBSMKT
--,UA_XORIMKT
--,UA_CANC
,(select dbo.BUSCADESC(UA_CODCANC)) MOTIVO_CANC
--,* 
from SUA010 SUA (NOLOCK)
--LEFT OUTER join SUB010 SUB (NOLOCK) ON UA_FILIAL = UB_FILIAL AND UA_NUM =UB_NUM AND SUB.D_E_L_E_T_='' AND SUA.D_E_L_E_T_=''
LEFT JOIN SA1010 SA1 (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= A1_FILIAL AND UA_CLIENTE=A1_COD AND UA_LOJA= A1_LOJA AND UA_PROSPEC='F' AND SA1.D_E_L_E_T_=''
LEFT JOIN SUS010 SUS (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= US_FILIAL AND UA_CLIENTE=US_COD AND UA_LOJA= US_LOJA AND UA_PROSPEC='T' AND SUS.D_E_L_E_T_=''
INNER JOIN SUH010 SUH (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= UH_FILIAL AND UA_MIDIA = UH_MIDIA AND SUH.D_E_L_E_T_=''
JOIN SA3010 SA3 (NOLOCK)ON  SUBSTRING(UA_FILIAL,1,4)=A3_FILIAL AND A3_COD =UA_VEND AND SA3.D_E_L_E_T_=''
JOIN SU5010 SU5 (NOLOCK)ON  SUBSTRING(UA_FILIAL,1,4)=U5_FILIAL AND U5_CODCONT = UA_CODCONT AND SU5.D_E_L_E_T_=''
WHERE 1=1
--and UA_XORIMKT<>''
--AND UA_NUM IN ('078124','078098','039078','078132')
--AND UA_CANC<>''
AND UH_DESC in('MARKETING','PORTAL')
--AND UA_VEND IN ('000021','000192','119072')
AND UA_VEND  BETWEEN '000021' AND '119072'
and UA_EMISSAO BETWEEN '20210101' AND '20210210'

 --Huélita (000021) e Bruna Ribeiro (000192)


 ORDER BY SUA.R_E_C_N_O_ DESC

--select * from SUS010

--SELECT * FROM SUA010

--SELECT * FROM SYP010
--WHERE YP_CAMPO='UA_CODCANC'
--AND YP_CHAVE='245447'

--SELECT * FROM SUH010


--SELECT dbo.BUSCADESC('245447')

--select * from SUA010
--WHERE UA_OPERADO ='000001'

--SELECT * FROM SA3010
--SELECT * FROM SU5010


-- Criação de Perguntas no arquivo SX1 – Cadastro de Perguntas:

--Pergunta

--De Filial ?

--Até Filial ?

--Grupo

--MNT310

--MNT310

--Ordem

--1

--2

--Tipo

--Caracter

--Caracter

--Tamanho

--8

--8

--https://tdn.totvs.com/pages/releaseview.action?pageId=6793504