SELECT 	
	 CASE WHEN UA_FILIAL ='010101' THEN 'TEGAPE'	
      WHEN UA_FILIAL ='010102' THEN 'TEGAPE COLOMBO'	
	 WHEN UA_FILIAL ='020101' THEN 'PROCESSO INDUSTRIAL'	
	 WHEN UA_FILIAL ='030101' THEN 'TEGAPE QUIMICA'	
	 WHEN UA_FILIAL ='030102' THEN 'TEGAPE QUIMICA CGS'	
	 END EMPRESA,	
	 UA_FILIAL,A3_NOME,		
	 (SELECT SUM(C6_VALOR)	
 	 FROM SC5010 SC5 (NOLOCK)	
 	 JOIN SC6010 SC6 (NOLOCK) ON C5_FILIAL=C6_FILIAL AND C6_NUM =C5_NUM AND SC5.D_E_L_E_T_='' AND SC6.D_E_L_E_T_=''	
 	 WHERE 1=1	
	 	AND C5_FILIAL = UA_FILIAL	
	 	AND C5_VEND1=UA_VEND	
	 	AND C5_EMISSAO BETWEEN '20210215' AND '20210215'	
	 )TOTAL_PEDIDOS,		
	 (SELECT COUNT(DISTINCT C5_NUM) QTD_PEDIDOS	
	  FROM SC5010 SC5 (NOLOCK)	
	  WHERE 1=1	
	 	AND C5_FILIAL = UA_FILIAL	
	 	AND C5_VEND1=UA_VEND	
	 	AND C5_EMISSAO BETWEEN '20210215' AND '20210215'	
	 	AND D_E_L_E_T_=''	
	 )QTD_PEDIDOS,	

	COUNT(DISTINCT ORÇAMENTOS)ORCAMENTOS,		
	COUNT(DISTINCT ATENDIMENTOS)ATENDIMENTOS,		
	COUNT(DISTINCT EMAIL)EMAIL,		
	COUNT(DISTINCT TELEFONE)TELEFONE,		
	COUNT(DISTINCT WHATSAPP)WHATSAPP,		
	COUNT(DISTINCT OUTRAS)OUTRAS	
	FROM(	
			SELECT UA_FILIAL,UA_VEND,A3_NOME,		
			CASE WHEN UA_OPER ='1' AND SC6_DELET='' THEN C6_VALOR ELSE 0 END TOTAL_PEDIDOS,	
			CASE WHEN UA_OPER ='1' THEN UA_NUM  END PEDIDOS,	
			CASE WHEN UA_OPER ='2' THEN UA_NUM  END ORÇAMENTOS,	
			CASE WHEN UA_OPER ='3' THEN UA_NUM END ATENDIMENTOS,	
			CASE WHEN UH_DESC IN('E-MAIL','EMAIL','E-mail') AND UA_OPER ='3' THEN UA_NUM  END EMAIL,		
			CASE WHEN UH_DESC ='TELEFONE'  AND UA_OPER ='3' THEN UA_NUM  END TELEFONE,		
			CASE WHEN UH_DESC ='WHATSAPP'  AND UA_OPER ='3' THEN UA_NUM END WHATSAPP,		
			CASE WHEN UH_DESC NOT IN('E-MAIL','EMAIL','E-mail','TELEFONE','WHATSAPP')  AND UA_OPER ='3' THEN UA_NUM  END OUTRAS,	
			UA_MIDIA	
			FROM(	
				SELECT UA_FILIAL, UA_VEND,A3_NOME,UA_NUM,UA_EMISSAO,UA_OPER,UA_MIDIA,ISNULL(C6_VALOR,0)C6_VALOR,SC6.D_E_L_E_T_ SC6_DELET 	
				FROM SUA010 SUA(NOLOCK)	
				JOIN SA3010 SA3 (NOLOCK)ON LEFT(UA_FILIAL,4) = A3_FILIAL AND A3_COD =UA_VEND AND SA3.D_E_L_E_T_=''	
				LEFT JOIN SC5010 SC5 (NOLOCK) ON UA_FILIAL = C5_FILIAL AND UA_NUMSC5=C5_NUM 	
				LEFT JOIN SC6010 SC6 (NOLOCK) ON C5_FILIAL=C6_FILIAL AND C5_NUM=C6_NUM AND SC5.D_E_L_E_T_=''	
				WHERE 1=1	
				AND UA_VEND >='000015'	
				AND UA_VEND <='000015'	
				AND UA_EMISSAO >= '20210215'	
				AND UA_EMISSAO <= '20210215'	
				AND UA_FILIAL >='030101'	
				AND UA_FILIAL <='030101'	
				AND SUA.D_E_L_E_T_=''	
				)AA	
			INNER JOIN SUH010 SUH (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= UH_FILIAL AND UA_MIDIA = UH_MIDIA AND SUH.D_E_L_E_T_=''
		)BB	
	GROUP BY UA_FILIAL,UA_VEND,A3_NOME	
	ORDER BY A3_NOME,UA_FILIAL	

	--SELECT * FROM SUH010
