
SELECT * FROM V_ATEND_MKT
	WHERE 1=1
	AND UA_FILIAL >=''
	AND UA_FILIAL <='ZZZZZZ'
	AND UA_VEND >=''
	AND UA_VEND <='ZZZZZZ'
	AND UA_EMISSAO >= '20200101'
	AND UA_EMISSAO <= '20210222'
	--AND MIDIA IN('MARKETING','PORTAL')
	AND (
		A3_NOME LIKE '%VIVIANE%'
		OR 
		A3_NOME LIKE '%DAIANE%'
		OR 
		A3_NOME LIKE '%DOROTHY%'
		)

