
SELECT 
UA_FILIAL EMPRESA,
UA_NUM ATENDIMENTO,
UA_NUMSC5 PEDIDO,
UA_DOC NOTA,
UA_CLIENTE CLIENTE,	
UA_LOJA LOJA,
CASE
WHEN UA_PROSPEC = 'F' THEN A1_NOME ELSE US_NOME END NOME,
UA_OPERADO OPERADOR,
UA_MIDIA MIDIA,
UA_VEND COD_VENDEDOR,
A3_NOME VENDEDOR,
 convert(varchar(10),convert(date,UA_EMISSAO,103),103) AS EMISSAO,
UA_PRTMLT PROTOCOLO_MULT
FROM SUA010 UA
LEFT OUTER JOIN SA1010 A1 ON A1_FILIAL = LEFT(UA_FILIAL,4) AND A1_COD = UA_CLIENTE AND A1_LOJA = UA_LOJA AND UA.D_E_L_E_T_ = '' AND A1.D_E_L_E_T_ = ''
LEFT OUTER JOIN SUS010 US ON US_FILIAL = LEFT(UA_FILIAL,4) AND US_COD = UA_CLIENTE AND US_LOJA = UA_LOJA AND US.D_E_L_E_T_ = ''
INNER JOIN SA3010 A3 ON A3_FILIAL = LEFT(UA_FILIAL,4) AND A3_COD = UA_VEND AND A3.D_E_L_E_T_ = ''	
WHERE 
1=1
AND UA_FILIAL = '010106' 
and UA_EMISSAO BETWEEN '20240830' AND '20240905'
AND UA_PRTMLT <> ''