SELECT B2_FILIAL FILIAL, B2_COD CODIGO,B1_DESC, B2_QATU	SALDO, ISNULL(D2_QUANT,0) QTD_VEND
FROM
(
	select B2_FILIAL, B2_COD, SUM(B2_QATU)B2_QATU
	--,* 
	from SB2010 SB2 (NOLOCK)
	GROUP BY B2_FILIAL, B2_COD
)AAA
LEFT OUTER JOIN 
(
	select D2_FILIAL, D2_COD, sum(D2_QUANT) D2_QUANT
	--, * 
	from SD2010 SD2 (NOLOCK)
	INNER JOIN SF2010 SF2 (NOLOCK) ON F2_FILIAL= D2_FILIAL AND F2_DOC=D2_DOC AND SF2.D_E_L_E_T_='' AND SD2.D_E_L_E_T_='' AND F2_TIPO NOT IN ('B','D')
	GROUP BY D2_FILIAL, D2_COD
)BBB ON B2_FILIAL=D2_FILIAL AND B2_COD=D2_COD
JOIN SB1010 SB1  (NOLOCK) ON B2_FILIAL=B1_FILIAL AND B2_COD=B1_COD AND SB1.D_E_L_E_T_=''
WHERE B2_FILIAL='010101'
AND B2_QATU>0
and ISNULL(D2_QUANT,0)=0
--AND B2_QATU-D2_QUANT>10 
ORDER BY 4 DESC

