ALTER view V_ATEND_MKT
AS
select 
UA_FILIAL
,UA_NUM
,UA_CLIENTE
,UA_LOJA
,case WHEN UA_PROSPEC='F' THEN 'CLIENTE' ELSE 'PROSPECT' END TIPO
,case WHEN UA_PROSPEC='F' THEN A1_NOME ELSE US_NOME END NOME
,case WHEN UA_PROSPEC='F' THEN A1_CGC ELSE US_CGC END CNPJ
,case WHEN UA_PROSPEC='F' THEN A1_EMAIL else US_EMAIL END EMAIL
,U5_CONTAT
,U5_CELULAR
,U5_FCOM1
,U5_EMAIL
,U5_FONE
,UH_DESC MIDIA
,UA_VEND
,A3_NOME
,CASE WHEN UA_OPER ='1' THEN 'FATURAMENTO'
	  WHEN UA_OPER ='2' THEN 'ORÇAMENTO'
	  ELSE 'ATENDIMENTO'
END OPERACAO
,UA_EMISSAO
,UA_INICIO
,UA_XMOBS
--,UA_XOBS
,CONVERT(varchar(MAX),CONVERT(VARBINARY(MAX), UA_XOBS)) as XOBS
,CONVERT(varchar(MAX),CONVERT(VARBINARY(MAX), UA_XOBSMKT)) as XOBSMKT
,(select dbo.BUSCADESC(UA_CODCANC)) MOTIVO_CANC
from SUA010 SUA (NOLOCK)
LEFT JOIN SA1010 SA1 (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= A1_FILIAL AND UA_CLIENTE=A1_COD AND UA_LOJA= A1_LOJA AND UA_PROSPEC='F' AND SA1.D_E_L_E_T_=''
LEFT JOIN SUS010 SUS (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= US_FILIAL AND UA_CLIENTE=US_COD AND UA_LOJA= US_LOJA AND UA_PROSPEC='T' AND SUS.D_E_L_E_T_=''
INNER JOIN SUH010 SUH (NOLOCK) ON SUBSTRING(UA_FILIAL,1,4)= UH_FILIAL AND UA_MIDIA = UH_MIDIA AND SUH.D_E_L_E_T_=''
JOIN SA3010 SA3 (NOLOCK)ON  SUBSTRING(UA_FILIAL,1,4)=A3_FILIAL AND A3_COD =UA_VEND AND SA3.D_E_L_E_T_=''
JOIN SU5010 SU5 (NOLOCK)ON  SUBSTRING(UA_FILIAL,1,4)=U5_FILIAL AND U5_CODCONT = UA_CODCONT AND SU5.D_E_L_E_T_=''
WHERE SUA.D_E_L_E_T_=''
 --ORDER BY SUA.R_E_C_N_O_ DESC
GO

SELECT * FROM V_ATEND_MKT
WHERE 1=1
AND UA_FILIAL ='010101'
AND MIDIA in('MARKETING','PORTAL')
AND UA_VEND  BETWEEN '000021' AND '119072'
and UA_EMISSAO BETWEEN '20210101' AND '20210210'



