

select A1_FILIAL, A1_COD, A1_NOME, A1_END, A1_NREDUZ
	, A1_BAIRRO, A1_EST, A1_CEP, A1_COD_MUN, A1_MUN
	, A1_DDD, A1_TEL, A1_CONTATO, A1_CGC, A1_EMAIL 
		from SA1010 
			where A1_NREDUZ like '%BUNGE%'


