

Select 'Janeiro', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-01-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-01-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '01' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '01'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '01'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3

UNION ALL
		
Select 'Fevereiro', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-02-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-02-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '02' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '02'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '02'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3

		UNION ALL
		
Select  'Março' ,Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-03-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-03-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '03' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '03'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '03'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3

UNION ALL
		
Select 'Abril', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-04-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-04-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '04' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '04'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '04'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3

UNION ALL
		
Select 'Maio', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-05-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-05-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '05' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '05'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '05'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3

UNION ALL
		
Select 'Junho', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-06-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-06-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '06' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '06'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '06'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras 
		WHERE 1=1
		) AS POTATO3

UNION ALL
		
Select 'Julho', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM
	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-07-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-07-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '07' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '07'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '07'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3

UNION ALL
		
Select 'Agosto', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-08-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-08-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '08' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '08'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '08'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3
UNION ALL
		
Select 'Setembro', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-09-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-09-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '09' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '09'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '09'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3
UNION ALL
		
Select 'Outubro', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-10-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-10-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '10' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '10'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '10'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3
UNION ALL
		
Select 'Novembro', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-11-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-11-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '11' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '11'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '11'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3
UNION ALL
		
Select 'Desembro', Funcionarios, Dias_Uteis, (Funcionarios * Dias_Uteis) AS Dias_Uteis_Totatis, Faltas_Injustificadas, Horas_Extras, CAST((CAST(Faltas_Injustificadas AS NUMERIC(10, 4)) / (Funcionarios * Dias_Uteis)) AS NUMERIC(10, 2)) AS INDICADOR FROM

	(SELECT 
		(SELECT COUNT(RA_MAT) AS POTATO FROM SRA010 WHERE RA_FILIAL  = '030102' AND RA_ADMISSA <= '2024-12-31' AND (RA_DEMISSA = '' OR RA_DEMISSA > '2024-12-31')AND D_E_L_E_T_ = '') AS Funcionarios,
		(SELECT COUNT(*) AS DATASET
			FROM (SELECT DISTINCT PH_DATA FROM SPH010 WHERE MONTH(PH_DATA) = '12' AND YEAR(PH_DATA) = '2024') AS Dias_Uteis
				WHERE 
					(CASE
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Monday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Tuesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Wednesday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Thursday' THEN 1
						WHEN DATENAME(WEEKDAY, PH_DATA) = 'Friday' THEN 1
						ELSE 0
					END) = 1
		) AS Dias_Uteis,
		(SELECT COUNT(*) FROM 
			(SELECT DISTINCT PH_MAT, CONVERT(VARCHAR(10), CONVERT(DATE,PH_DATA,103),103) PPdata, PH_ABONO
				FROM SPH010 SPH
					LEFT JOIN SP6010 SP6 ON P6_FILIAL = LEFT(PH_FILIAL,4) AND P6_CODIGO = PH_ABONO AND SP6.D_E_L_E_T_ = ''
					LEFT JOIN SP9010 SP9 ON P9_CODIGO = PH_PD
					WHERE PH_FILIAL = '030102'
						AND MONTH(PH_DATA) = '12'
						AND YEAR(PH_DATA) = '2024'
						AND PH_PD IN ('010')
						AND PH_ABONO = ''
						AND SPH.D_E_L_E_T_ = ''
				GROUP BY PH_MAT, PH_DATA, PH_ABONO
			) AS POTATO2
		) AS Faltas_Injustificadas,
		(SELECT SUM(PH_QUANTC)
			FROM SPH010 SPH
				INNER JOIN SP9010 SP9 ON P9_CODIGO = PH_PD AND P9_FILIAL = PH_FILIAL
					WHERE 1=1 
						AND PH_FILIAL = '030102'
						AND P9_CODFOL IN (	'150','151','152','153','154','155','156','157')
						AND MONTH(PH_DATA) = '12'
						AND YEAR(PH_DATA) = '2024'
		) AS Horas_Extras
		WHERE 1=1
		) AS POTATO3



