DECLARE @PRODUTO CHAR(20) = '029262'
DECLARE @CODCLI CHAR(6) = '105857'
DECLARE @LOJACLI CHAR(4) = '0001'



--Encontra o cliente
--SELECT A1_COD, A1_LOJA, A1_NOME, A1_NREDUZ, A1_TIPO, A1_PESSOA FROM SA1010 WHERE A1_NOME LIKE '%MOKVA%' AND D_E_L_E_T_ = ''

SELECT B1_GRTRIB, B1_GRPTI, B1_ORIGEM FROM SB1010 WHERE B1_COD = @PRODUTO AND D_E_L_E_T_ = ''
SELECT A1_GRPTRIB, A1_TIPO, A1_PESSOA, A1_CONTRIB, A1_SIMPLES FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = ''
--SELECT US_GRPTRIB,US_PESSOA,US_TIPO,* FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = ''
SELECT A1_EST FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = ''
SELECT US_EST FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = ''
--SELECT * FROM SX5010 WHERE X5_TABELA = '21'

DECLARE @GRUPO_PRODUTO CHAR(3) = (SELECT B1_GRTRIB FROM SB1010 WHERE B1_COD = @PRODUTO AND D_E_L_E_T_ = '')
DECLARE @GRUPO_CLIENTE CHAR(3) = (SELECT A1_GRPTRIB FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = '')
--DECLARE @GRUPO_CLIENTE CHAR(3) = (SELECT US_GRPTRIB FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = '')
DECLARE @ESTADO_CLIENTE CHAR(2) = (SELECT A1_EST FROM SA1010 WHERE A1_COD = @CODCLI AND A1_LOJA = @LOJACLI AND D_E_L_E_T_ = '')
--DECLARE @ESTADO_CLIENTE CHAR(2) = (SELECT US_EST FROM SUS010 WHERE US_COD=@CODCLI AND US_LOJA= @LOJACLI AND D_E_L_E_T_ = '')
DECLARE @OPERACAO CHAR(2) = '01'
DECLARE @FILIAL CHAR(2) = '010101'
DECLARE @GRPTI CHAR(4) = ''

--SELECT B1_CLASFIS,* FROM SB1010 WHEB1_CLASFISRE B1_COD='009996'

--SELECT *
--FROM SF7010
--WHERE 1=1
--AND D_E_L_E_T_ = ''
--AND F7_GRTRIB = '006'
--AND F7_EST = 'AM'
--AND F7_GRPCLI = '001'

--SELECT *
--FROM SFM010
--WHERE FM_FILIAL = '03'
--AND D_E_L_E_T_ = ''
--AND FM_TIPO = '03'
--AND FM_GRPROD = '013'
--AND FM_GRTRIB = '006'
--AND FM_GRPTI = ''

--OPERAÇÕES
--01: VENDA
--03: VENDA CONSUMIDOR FINAL

--SELECT * FROM SB2010 WHERE B2_COD = 'HLX1502V' AND B2_FILIAL = '04'

SELECT
	FM_TE
	,FM_TS
	,FM_PRODUTO				
	,FM_GRPROD				
	,FM_POSIPI				
	,FM_CLIENTE+FM_LOJACLI CLI_LOJA	
	,FM_GRTRIB				
	,FM_EST					
	,FM_REFGRD				
	,FM_GRPTI				
	,FM_TIPOCLI				
	,FM_GRPCST 				
	,FM_TIPOMOV				
	,*
FROM
	SFM010 FM
WHERE
	FM_FILIAL = ''
	--AND FM_PRODUTO = @PRODUTO
	--AND FM_GRTRIB = @GRUPO_CLIENTE
	AND FM_GRPROD = @GRUPO_PRODUTO
	AND FM_EST = @ESTADO_CLIENTE
	AND FM_TIPO = @OPERACAO
	AND FM_GRPTI = @GRPTI
	AND D_E_L_E_T_ = ''
	or (FM_TS='907'AND D_E_L_E_T_ = '')
	SELECT * FROM SA1010 WHERE A1_COD='105857'


	select * from SX6010
	WHERE X6_VAR='MV_OTICLI'
	--{1,2,3,4,5,6,7,8,9,10,11}
--FM_PRODUTO				Código de Produto							1
--FM_GRPROD					Grupo de Tributação do Produto				2
--FM_POSIPI					NCM											3
--FM_CLIENTE+FM_LOJACLI		Cliente+Loja Cliente						4
--FM_GRTRIB					Grupo Tributação							5
--FM_EST					Estado										6
--FM_REFGRD					Código de Referência da Grade				7
--FM_GRPTI					Grupo de TES Inteligente					8
--FM_TIPOCLI				Tipo de Cliente								9
--FM_GRPCST 				Código de enquadramento de IPI				10
--FM_TIPOMOV				Tipo de Movimentação do Pedido de Venda		11
